import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideMenu />
        <div className="w-full flex items-center justify-center bg-blue-50 ml-[220px]">
          <main className="max-w-[920px] flex flex-wrap items-center justify-center text-blue-800">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
